
# https://www.gnu.org/software/make/manual/make.html#Recursion


make:

	+make -C MirrorInitiator
	+make -C ContentMirrorServer 



clean:

	+cd MirrorInitiator && make clean
	+cd ContentMirrorServer && make clean
